hleb/cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove, order_show


app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('order/', order_show, name='order'),

]

hleb/cart/models.py
from django.db import models

# Create your models here.

hleb/cart/forms.py
from django import forms
from datetime import datetime

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=1, max_value=100)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)



class AdressForm(forms.Form):
    phonenumber = forms.CharField(label='Телефон', widget=forms.TextInput(attrs={'class': 'form-input'}), initial='+7')
    delivery = forms.BooleanField(label='Доставка', required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input', 'style': 'width: 20px; height: 20px;'}))
    adress = forms.CharField(label='Адрес', widget=forms.TextInput(attrs={'class': 'form-input'}))
    time_date = forms.DateTimeField(label='Дата и время', widget=forms.DateTimeInput(attrs={'class': 'form-input', 'type': 'datetime-local'}))
    comment = forms.CharField(label='Комментарий', required=False, widget=forms.Textarea(attrs={'class': 'form-input', 'placeholder': 'Введите комментарий к заказу, ваши пожелания, уточнения и прочее'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['delivery'].widget.attrs['onclick'] = "toggleAddressField()"
        self.fields['time_date'].widget.attrs['min'] = datetime.now().strftime('%Y-%m-%dT%H:%M')

hleb/cart/views.py
import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from django.contrib import messages

from .cart import Cart
from .forms import CartAddProductForm, AdressForm
from telegram import Bot
from django.conf import settings

flag = False
now = datetime.datetime.now()


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})


def order_show(request):

    cart = Cart(request)

    initial_values = {'adress': 'Самовывоз'}
    form = AdressForm(request.POST or None, initial=initial_values)

    if request.method == 'POST' and form.is_valid():
        phonenumber = form.cleaned_data['phonenumber']
        delivery = form.cleaned_data['delivery']
        adress = form.cleaned_data['adress']
        time_date = form.cleaned_data['time_date']
        email = request.user.email
        comment = form.cleaned_data['comment']


        order_info = []
        for item in cart.__iter__():
            order_info.append(f"{item['product'].title} ({item['quantity']} шт.)")

        message = f"Новый заказ:\nТелефон: {phonenumber}\n"
        message += f"Почта: {email}\n"
        if delivery:
            message += f"Адрес: {adress}\n"
        else:
            message += "Самовывоз\n"
        message += "Товары: " + "\n ".join(order_info) + "\n"
        message += f"Дата и время: {time_date}\n"
        if comment != '':
            message += f"Комментарий к заказу: {comment}\n"

        # Отправка сообщения через Telegram бота
        bot = Bot(token=settings.TELEGRAM_BOT_TOKEN)
        chat_id = settings.TELEGRAM_CHAT_ID
        bot.send_message(chat_id=chat_id, text=message)
        for item in cart.__iter__():
            cart_remove(request, item['product'].id)
        flag = True
        now = datetime.datetime.now()


        return redirect('home_page')


    return render(request, 'cart/order.html', {'cart': cart, 'form': form})

def flag():

    order_flag = {'flag': flag,
                  'now': now,

                  }

    return order_flag

hleb/cart/templates/cart/detail.html
{% extends "main/layout.html" %}
{% load static %}

{% block content %}
<div class="content">
    <div class="container ">
        <nav class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList"><span class="breadcrumbs__item d-inline-flex" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
							<a itemprop="item" class="breadcrumbs__link" href="/">
								<span itemprop="name">Главная</span>
							</a>
							<meta itemprop="position" content="1" />
						</span><span class="breadcrumbs__item d-inline-flex" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
							<a itemprop="item" class="breadcrumbs__link" href="/cart">
								<span itemprop="name">Корзина</span>
							</a>
							<meta itemprop="position" content="2" />
						</span></nav>
<h1>Корзина покупок</h1>
<table class="cart">

  <tbody>
  {% for item in cart %}
    {% with product=item.product %}
  <style>
      .cart_prod{
        text-align: center;
        margin: auto;
        padding: 10px;
        max-width: 200px;

      }
      .num{
        text-align: center;
        margin: auto;
        padding: 10px;
        max-width: 52px;

      }

  </style>
    <div style="background: #fffbef; display: flex; margin: auto; padding: 7px;">
      <div style="text-align: center;" class="cart_prod">

                <img src="{{ product.image.url }}" style="width: 56px;">

            </div>
            <div style="text-align: center;" class="cart_prod">{{ product.title }}</div>
            <div class="cart_prod">
                <style>
                    #id_quantity{
                        border-color: orange;
                        border-radius: 7px;
                        width: 40px;
                        text-align: center;
                    }


                </style>
              <form action="{% url 'cart:cart_add' product.id %}" method="post" class="form" class="cart_prod">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}

                  <button style="background: #fffbef; border: none;">
                    <img src="{% static 'cart/update.svg' %}" style="width: 23px; margin: auto;"
                  </button>

                {% csrf_token %}
              </form>
            </div >
            <div style="text-align: center;" class="cart_prod"><a href="{% url 'cart:cart_remove' product.id %}"><img src="{% static 'cart/delete.svg' %}" style="width: 30px; margin: auto;"></a></div>

            <div class="num cart_prod" style="text-align: center;">{{ item.cost }} ₽</div>

          </div>
        {% endwith %}
      {% endfor %}
      <div class="total" style="display: flex;">
          <style>
              .itog{
                    margin: auto;
              }

          </style>
        <div style="font-size: 30px; text-align: center;" class="itog" >Итого: </div>

        <div class="num itog" style="text-align: center; font-size: 30px;">{{ cart.get_total_price }} ₽</div>
      </div>
    </tbody>
  </table>
  <p class="text-right">
      <style>
          .aa {
                width: 30px;
          }
      </style>
      <a href="{% url 'home_page' %}" class="btn aa" style="margin: 5px; backgound: white; border-color: orangered; color: white;">В каталог</a>

      <style>
          <style>
    .empty-cart-message {
        position: absolute;
        top: -40px;
        left: 50%;
        transform: translateX(-50%);
        background-color: #ffcccc;
        color: #800000;
        padding: 10px;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }
</style>
      </style>
      <style>
          .loginimage{
                width: 30px;
                margin: 3px;
          }
      </style>

    {% if request.user.is_authenticated %}{% if cart %}
    <a href="order/"><button class="btn aa" style="width: 40px; margin: 5px; backgound: white; border-color: orangered; color: white">Оформить заказ</button></a>
{% else %}
    <button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-content="<div><img src='{% static 'cart/red_flag.svg' %}' class='loginimage'><span>Невозможно оформить заказ с пустой корзиной, добавьте товары</span></div>">Оформить заказ
  </button>
{% endif %}{% else %}<button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-content="<a href='{% url 'login' %}'><img src='{% static 'user/login.svg' %}' class='loginimage'><span>Войдите в аккаунт, чтобы оформить заказ</span></a>">
    Оформить заказ
  </button>{% endif %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
      return new bootstrap.Popover(popoverTriggerEl)
    })

  </script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </p>
    </div></div>
{% endblock %}

hleb/cart/templates/cart/order.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}

<div class="content">
  <div class="container">
    <nav class="breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList"><span class="breadcrumbs__item d-inline-flex" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
							<a itemprop="item" class="breadcrumbs__link" href="/">
								<span itemprop="name">Главная</span>
							</a>
							<meta itemprop="position" content="1" />
						</span><span class="breadcrumbs__item d-inline-flex" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
							<a itemprop="item" class="breadcrumbs__link" href="/cart/order">
								<span itemprop="name">Оформление заказа</span>
							</a>
							<meta itemprop="position" content="2" />
						</span></nav>
    <h1>Оформление заказа</h1>
    <form method="post">
      {% csrf_token %}
      <style>
        .helptext {
          display: none;
        }

        #id_phonenumber, #id_time_date, #id_adress, #id_comment{
          border-color: orangered;
          border-radius: 7px;
          height: 52px;
        }

        #id_delivery{
          width: 20px;
          heoght: 20px;
        }
        .form-label {
          display: inline-block;
          min-width: 200px;
          vertical-align: center;
        }

        .form-error {
          list-style: none;
          padding: 0;
          color: #CC0000;
        }
        #id_comment{
            padding: 9px;
            border-width: 2px;
            height: 150px;
            width: 350px;
            }

      </style>
      <script>
        function toggleAddressField() {
          var deliveryCheckbox = document.getElementById("id_delivery");
          var addressField = document.getElementById("id_adress");
          var commentField = document.getElementById("id_comment");

          if (deliveryCheckbox.checked) {
            addressField.style.display = "block";
            commentField.style.display = "block";
          } else {
            addressField.style.display = "none";
            commentField.style.display = "none";
          }
        }

      </script>
      <div class="form-error">{{ form.non_field_errors }}</div>
      {% for f in form %}
        {% if f.name == "delivery" %}
          <h4>
            {{ f }} <span onclick="toggleAddressField()">Заказать с доставкой</span>

          </h4>
        {% elif f.name != "adress" %}
          <h4>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}
          </h4>
        {% endif %}
        {% if f.name == "adress" %}
          <h4 style="display: none;" id="id_adress">
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}
          </h4>
          <h4 style="display: none; color: #fa8805;" id="id_comment"><label class="form-label">Обратите внимание, что сумма доставки зависит от вашего адреса и конечная стоимость заказа может измениться.</label></h4>
        {% endif %}
        <div class="form-error">{{ f.errors }}</div>
      {% endfor %}


      <button type="submit" class="btn">Оформить</button>
    </form>
      <a href="/cart" class="btn" style="margin-top: 30px; background: white; border-color: orangered; border-radius: 12px; color: black;">В корзину</a>
  </div>

</div>
{% endblock %}